import { documentDataType } from "@/types/types";
import { svgIcon } from "./svgIcon";
const { pdf, docCustomerIcon } = svgIcon;

export const documentsData:documentDataType[] = [
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    {
      name: "Product Requirements",
      type: "PDF",
      pdfimg:pdf,
      CustomerIcon:docCustomerIcon,
      author: "Earl Grayson",
      version: "1",
      status: "Archive",
      uploadedDate: "29 Jul 2023",
    },
    
   
  ]